version: "3.3"

services:
  nfs-server:
    image: gists/nfs-server
    container_name: nfs-server
    ports:
      - "2049:2049"
    # https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities
    cap_add:
      - SYS_ADMIN
      - SETPCAP
    environment:
      - "NFS_DOMAIN=*" # The visitor IP range
      - "NFS_OPTION=fsid=0,rw,sync,no_root_squash,all_squash,anonuid=0,anongid=0,no_subtree_check"
    volumes:
      - /share:/nfs-share
    restart: always
    privileged: true

